version: '3.3'
  
services:
    flask-app:
      build: .
      volumes:
        - .:/usr/src/app
      ports:
        - "5001:5000"
      depends_on:
        - my_db
    my_db:
      container_name: my_plpgdb
      hostname: my_db
      image: postgres
      ports:
        - "54321:5432"
      restart: unless-stopped
      environment:
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - /Users/shamanthkm/Documents/data:/var/lib/postgresql/data/
